# Generated by Django 3.2.7 on 2021-09-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('moviename', models.CharField(max_length=256)),
                ('movielink', models.CharField(max_length=128)),
                ('moviedescription', models.CharField(max_length=1024)),
                ('moviepicture', models.CharField(max_length=256)),
                ('movieview', models.CharField(max_length=64)),
                ('moviepop', models.CharField(max_length=64)),
                ('moviedate', models.CharField(max_length=64)),
                ('movielike', models.CharField(max_length=64)),
                ('moviecoin', models.CharField(max_length=64)),
                ('moviecollect', models.CharField(max_length=64)),
                ('shareInfo', models.CharField(max_length=64)),
                ('moviecomment1', models.CharField(max_length=1024)),
                ('moviecomment2', models.CharField(max_length=1024)),
                ('moviecomment3', models.CharField(max_length=1024)),
                ('moviecomment4', models.CharField(max_length=1024)),
                ('moviecomment5', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=64)),
                ('userlink', models.CharField(max_length=128)),
                ('userdescription', models.CharField(max_length=256)),
                ('userfan', models.CharField(max_length=64)),
                ('userpicture', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Movies from bilibili',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('userlink', models.CharField(max_length=128)),
                ('userdescription', models.CharField(max_length=256)),
                ('userfan', models.CharField(max_length=64)),
                ('userpicture', models.CharField(max_length=256)),
                ('movies', models.ManyToManyField(to='bilibili.Movie')),
            ],
            options={
                'verbose_name_plural': 'Users from bilibili',
            },
        ),
    ]
